import dayjs from 'dayjs';

function getTime(day = 0, second = 0) {
  return dayjs()
    .add(day, 'days')
    .add(second, 'seconds')
    .format('YYYY.MM.DD HH:mm:ss');
}

export const initData = async (clientId, nextSeq) => {
  return {
    // 회원
    user: [
      {
        _id: await nextSeq('user'),
        email: 'admin@market.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '무지',
        phone: '010-1111-2222',
        postcode: '03666',
        addressDetail1: '서울 서대문구 증가로8길 42-2',
        addressDetail2: '111동 111호',
        type: 'admin',
        loginType: 'email',
        image: `files/${clientId}/profile-1.png`,
        createdAt: getTime(-100, -60 * 60 * 3),
        updatedAt: getTime(-100, -60 * 60 * 3),
        extra: {
          birthday: '03-23',
        },
      },
      {
        _id: await nextSeq('user'),
        email: 'habit2me@naver.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '김영호',
        phone: '010-2222-3333',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        loginType: 'email',
        image: `files/${clientId}/seller-2.jpg`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
        extra: {
          birthday: '11-23',
          farmName: '달그락 농장',
          info: [
            '자연의 흐름에 따라 농사짓는 이곳은, 하루를 새벽 이슬을 밟으며 시작하는 조용한 농장입니다.',
            '빠르게 자라고, 보기 좋게 생긴 작물보다는 시간이 걸려도 자연스럽고 튼튼하게 자란 작물을 더 소중히 여깁니다.',
            '수확은 늘 손으로 직접 이루어지며, 거친 겉모습 속에 담긴 땅의 온기와 정직함을 소비자에게 그대로 전달하고 싶어 합니다.',
            '땀 흘린 만큼 믿을 수 있는 결과물을 드리는 것이 농장주의 오랜 신념이자 자부심입니다.',
          ],
        },
      },
      {
        _id: await nextSeq('user'),
        email: 'habit2me@naver.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '박진희',
        phone: '010-2222-3333',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        loginType: 'email',
        image: `files/${clientId}/seller-3.jpg`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
        extra: {
          birthday: '11-23',
          farmName: '초록숨결 농원',
          info: [
            '초록 숨결이라는 이름처럼, 작물도 땅도 살아 숨 쉬는 공간을 만들기 위해 매일 땀 흘리는 농원입니다.',
            '농약을 사용하지 않고, 생태계와 조화를 이루며 자란 작물들의 자연스러운 생김새를 있는 그대로 존중합니다.',
            '수확부터 선별, 포장까지 모든 과정에 손이 많이 가지만, 그만큼 작물 하나하나에 애정을 담고 있습니다.',
            '흠집 많고 크기 제멋대로인 농산물이라도 그 속에 담긴 건강함만큼은 자신 있게 전할 수 있어요.',
          ],
        },
      },
      {
        _id: await nextSeq('user'),
        email: 'habit2me@naver.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '이도윤',
        phone: '01022223333',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        loginType: 'email',
        image: `files/${clientId}/seller-4.jpg`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
        extra: {
          birthday: '11-23',
          farmName: '흙내음터',
          info: [
            '도시 생활을 뒤로하고 귀농을 결심한 농부가 정성껏 일군, 흙내음 가득한 작지만 따뜻한 터전입니다.',
            '땅의 성질과 계절의 흐름을 직접 느끼며 농사짓는 이곳은, 울퉁불퉁한 작물 하나에도 수많은 이야기가 담겨 있어요.',
            '예쁘고 반듯한 농산물만을 찾는 시대지만, 이곳에선 불완전함도 자연의 일부로 존중받습니다.',
            '기계보다는 손을, 수량보다는 진심을 믿으며, 매일 조금씩 더 나은 농장을 만들어가고 있습니다.',
          ],
        },
      },
      {
        _id: await nextSeq('user'),
        email: 'habit2me@naver.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '정미라',
        phone: '01022223333',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        loginType: 'email',
        image: `files/${clientId}/seller-5.jpg`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
        extra: {
          birthday: '11-23',
          farmName: '바람골 농장',
          info: [
            '산자락 바람이 스며드는 골짜기 마을에 자리한 이 농장은, 자연의 흐름에 맞춰 작물을 키우는 가족 중심 농장입니다.',
            '기계보다 손을, 속도보다 계절의 흐름을 믿으며, 하루하루 자연과 호흡하며 살아가는 방식으로 농사짓고 있어요.',
            '보기엔 투박하지만 속이 알찬 작물들을 정성스럽게 가꾸며, 자식 키우듯 작은 손길 하나하나에 마음을 담습니다.',
            '누구나 안심하고 먹을 수 있도록, 땀과 정직함으로 수확한 농산물만을 소비자에게 전합니다.',
          ],
        },
      },
      {
        _id: await nextSeq('user'),
        email: 'habit2me@naver.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '조규태',
        phone: '01022223333',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        loginType: 'email',
        image: `files/${clientId}/seller-6.jpg`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
        extra: {
          birthday: '11-23',
          farmName: '느린손 농장',
          info: [
            '‘빠르게’보다 ‘바르게’를 먼저 생각하는 농장으로, 모든 작물에 농장주의 느리고 단단한 손길이 닿아 있습니다.',
            '자연의 시간표에 맞춰 천천히 자란 작물들은 비록 투박하게 생겼지만 깊은 맛과 생명력을 간직하고 있어요.',
            '농약이나 비료에 의존하지 않고, 매일 상태를 살피며 손으로 관리하는 방식은 고되지만 가장 믿을 수 있습니다.',
            '그 어떤 작물도 서두르지 않고 기다려주는 마음, 그것이 이 농장을 특별하게 만드는 가장 큰 이유입니다.',
          ],
        },
      },
    ],

    // 상품
    product: [
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근1',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이2',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 4,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯3',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 5,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근4',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 6,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이5',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯6',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근7',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 4,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이8',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 5,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯9',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 6,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근10',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이11',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯12',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 4,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근13',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 5,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이14',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 6,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯15',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근16',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이17',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 4,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯18',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 5,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근19',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 6,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이20',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯21',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근22',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 4,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이23',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 5,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯24',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 6,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근25',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이26',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯27',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 4,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근28',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 5,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이29',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 6,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯30',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근31',
        quantity: 320,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
          info: [
            '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
            '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
            '크기가 다양하고 모양이 개성 있어요.',
          ],
          storage: ['습기 없이 냉장보관 / 5일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 3,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마답답이32',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
          info: [
            '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
            '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
            '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
          ],
          storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 4,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯33',
        quantity: 200,
        buyQuantity: 0,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
          info: [
            '구이에 빠질 수 없는 버섯이죠. 하얀 양송이버섯보다 맛과 향이 진하고 쫄깃한 식감을 느낄 수 있어요. 볶음, 파스타, 수프, 등 한식과 양식 모두 잘 어울려요.',
            '크기가 아담하고 모양이 개성 있어요.',
          ],
          storage: ['습기없이 냉장보관 / 3일'],
        },
      },
    ],

    // 주문
    order: [
      {
        _id: await nextSeq('order'),
        products: [
          {
            _id: 1,
            quantity: 2,
            seller_id: 2,
            name: '바니바니바니바니 당근당근1',
            image: {
              path: '/files/febc13-final13-emjf/product-1.jpeg',
              name: 'product-1.jpeg',
              originalname: 'product-1.jpeg',
            },
            price: 3980,
            size: null,
            color: null,
            extra: {
              isBest: true,
              category: ['당근', '채소'],
              details: '150g',
              info: [
                '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
                '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
                '크기가 다양하고 모양이 개성 있어요.',
              ],
              storage: ['습기 없이 냉장보관 / 5일'],
            },
          },
        ],
        user: {
          name: '무지',
          phone: '010-1111-2222',
          postcode: '03666',
          addressDetail1: '서울 서대문구 증가로8길 42-2',
          addressDetail2: 'ㅁㄴㅇ',
          message: 'ㅁㄴㅇ',
        },
        payment: '네이버페이',
        total: '3980',
        state: 'OS020',
        user_id: 1,
        createdAt: '2025.07.31 10:14:20',
        updatedAt: '2025.07.31 10:14:20',
        cost: {
          products: 3980,
          shippingFees: 0,
          discount: {
            products: 0,
            shippingFees: 0,
          },
          total: 3980,
        },
      },
      {
        _id: await nextSeq('order'),
        products: [
          {
            _id: 2,
            quantity: 1,
            seller_id: 3,
            name: '고구마 답답이2',
            image: {
              path: '/files/febc13-final13-emjf/product-2.jpeg',
              name: 'product-2.jpeg',
              originalname: 'product-2.jpeg',
            },
            price: 2990,
            size: null,
            color: null,
            extra: {
              isBest: true,
              category: ['고구마', '과일'],
              details: '500g',
              info: [
                '언제 먹어도 맛있는 건강간식이죠. 굽거나 쪄 고구마의 달콤함과 포슬함을 입안 가득 느껴보세요.',
                '크기가 아담하거나 우람하고, 모양이 개성 있어요.',
                '토양 및 재배 환경에 따라 자라는 과정에서 표면에 검은 무늬가 생기기도 해요. 인체에 무해하기 때문에 안심하고 드셔도 좋아요.',
              ],
              storage: ['12-15도의 서늘하고 통풍이 잘 되는 곳에서 보관 / 7일'],
            },
          },
          {
            _id: 1,
            quantity: 1,
            seller_id: 2,
            name: '바니바니바니바니 당근당근1',
            image: {
              path: '/files/febc13-final13-emjf/product-1.jpeg',
              name: 'product-1.jpeg',
              originalname: 'product-1.jpeg',
            },
            price: 1990,
            size: null,
            color: null,
            extra: {
              isBest: true,
              category: ['당근', '채소'],
              details: '150g',
              info: [
                '큰 당근을 깎거나 수확시기를 앞당겨 작게 만든 당근이 아니에요. 품종부터 아담한 스낵당근은 아삭한 식감과 은은한 단맛을 가지고 있어요. 한 손에 쏘옥 들어오는 크기로 간식처럼 즐기기 좋아요.',
                '당근이 자라면서 상대적으로 햇빛에 많이 노출될 경우 윗부분이 초록빛을 띌 수 있어요. 드시는 데에는 문제가 없으니 안심하고 이용하셔도 좋아요.',
                '크기가 다양하고 모양이 개성 있어요.',
              ],
              storage: ['습기 없이 냉장보관 / 5일'],
            },
          },
        ],
        user: {
          name: '무지',
          phone: '010-1111-2222',
          postcode: '03666',
          addressDetail1: '서울 서대문구 증가로8길 42-2',
          addressDetail2: '어딘가',
          message: '네',
        },
        payment: '토스페이',
        total: '4980',
        state: 'OS020',
        user_id: 1,
        createdAt: '2025.07.31 10:20:01',
        updatedAt: '2025.07.31 10:20:01',
        cost: {
          products: 4980,
          shippingFees: 0,
          discount: {
            products: 0,
            shippingFees: 0,
          },
          total: 4980,
        },
      },
    ],

    // 후기
    review: [],

    // 장바구니
    cart: [
      {
        _id: await nextSeq('cart'),
        user_id: 1,
        product_id: 1,
        quantity: 2,
        createdAt: getTime(-7, -60 * 30),
        updatedAt: getTime(-7, -60 * 30),
      },
    ],

    // 즐겨찾기/북마크
    bookmark: [
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        user: {
          _id: 4,
          name: '제이지',
          image: `files/${clientId}/user-jayg.webp`,
        },
        type: 'product',
        target_id: 1,
        memo: '첫째 크리스마스 선물.',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        user: {
          _id: 4,
          name: '제이지',
          image: `files/${clientId}/user-jayg.webp`,
        },
        type: 'product',
        target_id: 2,
        memo: '둘째 생일 선물',
        createdAt: getTime(-1, -60 * 60 * 12),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        user: {
          _id: 4,
          name: '제이지',
          image: `files/${clientId}/user-jayg.webp`,
        },
        type: 'post',
        target_id: 1,
        memo: '크기 문의글 북마크',
        createdAt: getTime(-1, -60 * 60 * 12),
      },
    ],

    // 코드
    code: [],

    // 설정
    config: [],
  };
};
